/**
 * review.api.js — org review parity + remediation API surface.
 *
 * All calls go to ReviewController endpoints (/v1/assessments/...).
 * Separate from assessments.api.js to keep the surface clean and
 * to avoid one giant file. Frontend imports from both.
 */

import api from '../config/axios.config'

export const reviewApi = {

  // ── REVIEWER SECTION MANAGEMENT ──────────────────────────────────────────

  /** Org CISO assigns a section to a reviewer (writes reviewerAssignedUserId) */
  reviewerAssignSection: (assessmentId, sectionInstanceId, userId) =>
    api.put(`/v1/assessments/${assessmentId}/sections/${sectionInstanceId}/reviewer-assign`,
      { userId }),

  /** Reviewer fetches their assigned sections with questions */
myReviewerSections: (assessmentId, taskId) =>
  api.get(`/v1/assessments/${assessmentId}/my-reviewer-sections`,
    { params: taskId ? { taskId } : {} }),

  /** Reviewer submits their section (stamps reviewerSubmittedAt, fires gate) */
  reviewerSubmitSection: (assessmentId, sectionInstanceId, taskId) =>
    api.post(`/v1/assessments/${assessmentId}/sections/${sectionInstanceId}/reviewer-submit`,
      null, { params: taskId ? { taskId } : {} }),

  /** Org CISO reopens a reviewer's submitted section */
  reviewerReopenSection: (assessmentId, sectionInstanceId) =>
    api.post(`/v1/assessments/${assessmentId}/sections/${sectionInstanceId}/reviewer-reopen`),

  // ── REVIEW ASSISTANT SUB-TASKS ────────────────────────────────────────────

  /**
   * Reviewer assigns question to review assistant.
   * USE THIS instead of the old reviewerAssignQuestion — this one also creates the inbox sub-task.
   */
  reviewerAssignQuestionWithTask: (assessmentId, questionInstanceId, userId) =>
    api.put(`/v1/assessments/${assessmentId}/questions/${questionInstanceId}/reviewer-assign-v2`,
      { userId }),

  /** Reviewer unassigns review assistant from a question */
  reviewerUnassignQuestion: (assessmentId, questionInstanceId) =>
    api.delete(`/v1/assessments/${assessmentId}/questions/${questionInstanceId}/reviewer-assign`),

  /** Review assistant submits their section group evaluations */
  assistantSubmitSection: (assessmentId, sectionInstanceId, taskId) =>
    api.post(`/v1/assessments/${assessmentId}/sections/${sectionInstanceId}/assistant-submit`,
      null, { params: taskId ? { taskId } : {} })
       .then(r => r.data?.data ?? r.data),

  /** Review assistant's section submission status */
  assistantSectionStatus: (assessmentId) =>
    api.get(`/v1/assessments/${assessmentId}/assistant-section-status`)
       .then(r => r.data?.data ?? r.data),

  // ── CLARIFICATION & REMEDIATION ───────────────────────────────────────────

  /**
   * Reviewer sends a question back to review assistant for clarification.
   * Internal — does NOT involve the vendor.
   * Body: { description: string }
   */
  requestClarification: (assessmentId, questionInstanceId, description) =>
    api.post(`/v1/assessments/${assessmentId}/questions/${questionInstanceId}/request-clarification`,
      { description }),

  /**
   * Reviewer requests vendor remediation on a specific question.
   * Creates a REMEDIATION_REQUEST action item → appears in vendor fill page.
   * Body: { severity, description, expectedEvidence?, dueDate? }
   */
  requestRemediation: (assessmentId, questionInstanceId, payload) =>
    api.post(`/v1/assessments/${assessmentId}/questions/${questionInstanceId}/request-remediation`,
      payload),

  /**
   * Reviewer accepts risk on an open remediation item.
   * Closes the item without requiring vendor to fix it.
   * Body: { note: string }
   */
  acceptRisk: (assessmentId, actionItemId, note) =>
    api.post(`/v1/assessments/${assessmentId}/action-items/${actionItemId}/accept-risk`,
      { note }),

  /**
   * Reviewer validates that vendor's remediation is satisfactory.
   * Resolves the action item. May trigger report re-generation.
   * Body: { note?: string }
   */
  validateRemediation: (assessmentId, actionItemId, note) =>
    api.post(`/v1/assessments/${assessmentId}/action-items/${actionItemId}/validate-remediation`,
      { note }),

  // ── REPORT VERSIONING ─────────────────────────────────────────────────────

  /**
   * Manually generate or re-generate the assessment report.
   * v1 is auto-generated by the workflow automation at CISO approval.
   * v2+ are generated here after remediations close or manually.
   * Body: { remarks?: string }
   */
  generateReport: (assessmentId, remarks) =>
    api.post(`/v1/assessments/${assessmentId}/generate-report`,
      { remarks: remarks || '' })
       .then(r => r.data?.data ?? r.data),

  /** Get all report versions for an assessment */
  getReports: (assessmentId) =>
    api.get(`/v1/assessments/${assessmentId}/reports`)
       .then(r => r.data?.data ?? r.data),
}